import type { Metadata } from "next";
import "./globals.css";
import './tailwind.css';
import {ReactNode} from "react";
import localFont from "next/font/local";
import ToastContainer from "@/components/provider/ToastProvider";
import LoadingProvider from "@/components/provider/LoadingProvider";
import Dialog from "@/components/Dialog";

export const metadata: Metadata = {
  title: "STARBOY | 동아리의 성공을 위해",
  description: "Generated by cher1sh-next-app",
};

const pretendard = localFont({
  src: '../assets/fonts/pretendard.woff2',
  variable: "--font-prendard",
  weight: "100 900",
  display: 'swap'
});

const anton = localFont({
  src: '../assets/fonts/anton.woff2',
  variable: "--font-antonfont",
  weight: "100 900",
  display: 'swap'
});


const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} ${anton.variable}`}>
        <ToastContainer />
        <LoadingProvider color="var(--color-primary)" />
        <div className="w-full min-h-screen bg-bg text-white">{children}</div>
        <Dialog />
      </body>
    </html>
  );
}

export default RootLayout;