import type { Metadata } from "next";
import "./globals.css";
import './tailwind.css';
import {ReactNode} from "react";
import localFont from "next/font/local";
import {CookiesProvider} from "next-client-cookies/server";
import QueryProvider from "@/components/provider/QueryProvider";
import ToastContainer from "@/components/provider/ToastProvider";
import LoadingProvider from "@/components/provider/LoadingProvider";
import Dialog from "@/components/Dialog";

export const metadata: Metadata = {
  title: "STARBOY | 동아리의 성공을 위해",
  description: "Generated by cher1sh-next-app",
};

const pretendard = localFont({
  src: "../assets/fonts/pretendard.woff2",
  variable: "--font-prendard",
  weight: "100 900",
});


const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className={pretendard.variable}>
        <ToastContainer />
        <LoadingProvider color="var(--color-primary)" />
        <QueryProvider>
          <CookiesProvider>
            <div className="w-full min-h-screen bg-bg text-white">{children}</div>
            <Dialog />
          </CookiesProvider>
        </QueryProvider>
      </body>
    </html>
  );
}

export default RootLayout;